### ISSUE TITLE
Ill-formed samples in the test suite

### ISSUE THREAD

**Issue by i-to** [burnson/belle#5]
I've noticed that some samples in the test suite don't render deterministically. 

In particular, the encircled example in the figure below sometimes comes out with two sharps. The reason is that the actual notes are CSharp3 and CFlat3. Apparently, the engraver is not prepared for such a case and the first accidental that comes out during chord notes traversal wins. 

The order of traversal appears to be non-deterministic (probably, because node/edge pointers are used as keys in the tree).

![image](https://user-images.githubusercontent.com/8507472/51561038-e3f22f80-1e8e-11e9-978d-4c8bebe5eb38.png)

**Comment by burnson** [comment]
Thanks for reporting this @i-to. The part state accumulator did not consider the possibility that there could be more than one accidental being emitted per staff position. This led to an arbitrary tie-break that was dependent, as you found, on the internal graph representation. In [this commit](
https://github.com/burnson/belle/commit/106f1ec370191c8e7e779d8e130bb724ac2b32ed) I have updated the part state accumulator to keep a set of emitted accidentals per staff position.
